// <auto-generated />
namespace AssistVente.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _default : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_default));
        
        string IMigrationMetadata.Id
        {
            get { return "202001301911257_default"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
